In [1]:
#### THIS NOTEBOOK TESTS SOME FUNCTIONALITY

In [2]:
# Expanding visibility zone for Python engine to make HH Modules seen
import sys 
sys.path.append('../..')

# Importing standard modules and date-special modules
import numpy as np
from sklearn.decomposition import PCA

In [28]:
# Quantity of source basis parameters = 2 (m)
# Quantity of measurements = 3 (n)
x = np.array([2, 4, 0]) # m = 1
y = np.array([5, 1, 3]) # m = 2
z = np.column_stack((x, y)) # Table of observations (m * n)

# n_components - Quantity of basis PCA vectors we need (n_c)
# Initializing of PCA module
pca = PCA(n_components = 1) # n_c
# PCA performing
pca.fit(z)

# Matrix of coefficients (n_c * m) for source basis
print(pca.components_)

# The amount of variance explained by each of the pca
print(pca.explained_variance_)
print(pca.explained_variance_ratio_)
print(pca.noise_variance_) 

#The singular values corresponding to each of the selected components.
print(pca.singular_values_)

[[ 0.70710678 -0.70710678]]
[6.]
[0.75]
2.0
[3.46410162]


In [33]:
# Quantity of source basis parameters = 2 (m)
# Quantity of measurements = 3 (n)
x = np.array([0, 0, 0]) # m = 1
y = np.array([5, 1, 3]) # m = 2
z = np.column_stack((x, y)) # Table of observations (m * n)

# n_components - Quantity of basis PCA vectors we need (n_c)
# Initializing of PCA module
pca = PCA(n_components = 1) # n_c
# PCA performing
pca.fit(z)

# Matrix of coefficients (n_c * m) for source basis
print(pca.components_)

# The amount of variance explained by each of the pca
print(pca.explained_variance_)
print(pca.explained_variance_ratio_)
print(pca.noise_variance_) 

#The singular values corresponding to each of the selected components.
print(pca.singular_values_)

[[0. 1.]]
[4.]
[1.]
0.0
[2.82842712]


In [36]:
# Quantity of source basis parameters = 2 (m)
# Quantity of measurements = 3 (n)
x = np.array([2, 4, 0]) # m = 1
y = np.array([2, 4, 0]) # m = 2
z = np.column_stack((x, y)) # Table of observations (m * n)

# n_components - Quantity of basis PCA vectors we need (n_c)
# Initializing of PCA module
pca = PCA(n_components = 1) # n_c
# PCA performing
pca.fit(z)

# Matrix of coefficients (n_c * m) for source basis
print(pca.components_)

# The amount of variance explained by each of the pca
print(pca.explained_variance_)
print(pca.explained_variance_ratio_)
print(pca.noise_variance_) 

#The singular values corresponding to each of the selected components.
print(pca.singular_values_)

[[0.70710678 0.70710678]]
[8.]
[1.]
6.287222435018161e-32
[4.]


In [37]:
# Quantity of source basis parameters = 2 (m)
# Quantity of measurements = 3 (n)
x = np.array([2, 4, 0]) # m = 1
y = np.array([0, 4, 2]) # m = 2
z = np.column_stack((x, y)) # Table of observations (m * n)

# n_components - Quantity of basis PCA vectors we need (n_c)
# Initializing of PCA module
pca = PCA(n_components = 1) # n_c
# PCA performing
pca.fit(z)

# Matrix of coefficients (n_c * m) for source basis
print(pca.components_)

# The amount of variance explained by each of the pca
print(pca.explained_variance_)
print(pca.explained_variance_ratio_)
print(pca.noise_variance_) 

#The singular values corresponding to each of the selected components.
print(pca.singular_values_)

[[0.70710678 0.70710678]]
[6.]
[0.75]
2.0
[3.46410162]
